#!/bin/bash

# Initialization script for Mithlond

# Copyright (C) 2015 Xavier Gendre

# This file is part of Mithlond.

# Mithlond is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Mithlond is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Mithlond. If not, see <http://www.gnu.org/licenses/>.

echo 1 > /sys/fs/cgroup/cpuset/cgroup.clone_children

if [ -f MITHLOND_CONF_DIR/mithlond.conf ]; then
  source <(cat MITHLOND_CONF_DIR/mithlond.conf | grep ^USERS)
  USER_LIST=$(echo $USERS | tr ":" "\n")
  for U in $USER_LIST; do
    mithlond create mithlond-$U
    mithlond chown $U mithlond-$U
    U_HOME=$(eval echo ~$U)
    [ -d $U_HOME ] || (echo "cannot get home directory for $U"; exit 1)
    lxc-autostart -L -P $U_HOME/.local/share/lxc | while read LUNT; do
      set -- $LUNT
      su $U --command "mithlond start mithlond-$U $1"
      sleep $2
    done
  done
fi
