#!/bin/bash

# Uninstallation script for Mithlond

# Copyright (C) 2015 Xavier Gendre

# This file is part of Mithlond.

# Mithlond is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Mithlond is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Mithlond. If not, see <http://www.gnu.org/licenses/>.

source mithlond.config

rm -f $MITHLOND_CONF_DIR/mithlond.conf
systemctl disable mithlond.service
rm -f /lib/systemd/system/mithlond.service
rm -f /lib/systemd/mithlond
rm -f /etc/sysctl.d/mithlond.conf
rm -f $MITHLOND_BIN_DIR/mithlond
